name: Validar HTML

on:
  push:
    branches:
      - main

jobs:
  validar-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validar HTML
        uses: EndBug/html-validator@v1
        with:
          files: '**/*.html'

